#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2026 Ana Flo <anaflom@gmail.com>
#
# SPDX-License-Identifier: BSD-3-Clause

"""Within-mouse classification on pre-cached shuffled zigzag vectorizations.

Requires shuffles to be pre-generated by generate_trials_ablation_shuffle.py.

Preflight checks (all run before any training):
  1. Each mouse has at least --n-shuffles available randomizations for the
     requested shuffle-type / configuration.  Fails with an explicit message
     listing which mice have too few and how many are missing.
  2. Shuffle manifests indicate generation used at least --max-trials.
     Fails if any mouse/shuffle was generated with fewer trials than requested.
  3. Randomly samples exactly --n-shuffles IDs from each mouse's available
     pool (seeded by --seed for reproducibility).

Outputs per run folder:
  within_mouse_ablation_shuffle_metrics.json
  within_mouse_ablation_shuffle_metrics.csv
  figures/   (confusion matrices)
  logs/run.log

Usage examples
--------------
  python classify_trials_within_mouse_ablation_shuffle.py \\
         --output-folder results/ablation_shuffle/time/p30-per-trial/within_run1 \\
         --n-shuffles 5 --shuffle-type time

  python classify_trials_within_mouse_ablation_shuffle.py \\
         --output-folder results/ablation_shuffle/time/p30-per-trial/within_run2 \\
         --n-shuffles 10 --shuffle-type time --max-trials 200 --seed 0
"""

from __future__ import annotations

import argparse
import csv
import gc
import json
import random
import sys
import traceback
from contextlib import redirect_stderr, redirect_stdout
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import DataLoader, Subset

from classification_models import (
    CNN3D,
    GridTrialDataset,
    run_logreg_cv,
    run_nn_cv,
)
from shuffle_utils import validate_mice_for_ablation
from utils import (
    _build_zz_folder,
    _discover_mice,
    _opt_csv_list,
    _opt_int,
    _resolve_mouse_cache_dir,
    _short_mouse_name,
    _str2bool,
    build_vectorization_cache_stem,
    load_labelled_barcodes,
    load_labelled_grid_paths,
    load_vectorization_cache,
)


# ---------------------------------------------------------------------------
# Cache index helpers (mirrors generate script)
# ---------------------------------------------------------------------------

def _shuffle_cache_stem(base_stem: str, shuffle_type: str) -> str:
    return f"{base_stem}_{shuffle_type}"


def _shuffle_mode_token(different_shuffle_per_trial: bool) -> str:
    return "different" if different_shuffle_per_trial else "same"


def _shuffle_cache_stem_with_mode(
    base_stem: str,
    shuffle_type: str,
    shuffle_id: int,
    different_shuffle_per_trial: bool,
) -> str:
    mode_token = _shuffle_mode_token(different_shuffle_per_trial)
    return f"{_shuffle_cache_stem(base_stem, shuffle_type)}_{mode_token}_shuffle{shuffle_id:04d}"


def _existing_shuffle_ids(
    cache_dir: Path,
    base_stem: str,
    shuffle_type: str,
    different_shuffle_per_trial: bool,
) -> List[int]:
    ids = []
    stem_prefix = _shuffle_cache_stem(base_stem, shuffle_type)
    mode_token = _shuffle_mode_token(different_shuffle_per_trial)
    for p in cache_dir.glob(f"{stem_prefix}_{mode_token}_shuffle*.npz"):
        stem = p.stem
        try:
            idx = int(stem.rsplit("shuffle", 1)[1])
            ids.append(idx)
        except (IndexError, ValueError):
            pass
    return sorted(ids)


MANIFEST_FILENAME = "shuffle_manifest.json"


def _latest_manifest_path(cache_dir: Path, shuffle_type: str) -> Optional[Path]:
    legacy = cache_dir / MANIFEST_FILENAME
    if legacy.exists():
        return legacy
    return None


def _load_manifest(cache_dir: Path, shuffle_type: str) -> Dict[str, Any]:
    mp = _latest_manifest_path(cache_dir, shuffle_type)
    if mp is not None:
        with open(mp, encoding="utf-8") as fp:
            return json.load(fp)
    return {}


def _manifest_key(
    shuffle_type: str,
    method: str,
    p_active: int,
    per_trial_thresh: bool,
    clip_frames: int,
    different_shuffle_per_trial: bool,
) -> str:
    pt = "pertrial1" if per_trial_thresh else "pertrial0"
    mode_token = _shuffle_mode_token(different_shuffle_per_trial)
    return f"{shuffle_type}__{method}__{p_active}__{pt}__clip{clip_frames}__shufflemode-{mode_token}"


# ---------------------------------------------------------------------------
# Argument parser
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Within-mouse classification on pre-cached shuffled vectorizations"
    )
    p.add_argument("--output-folder", type=Path, required=True)
    p.add_argument("--data-root", type=Path, required=True)
    p.add_argument("--meta-root", type=Path, required=True)
    p.add_argument("--cache-dir", type=lambda x: Path(x) if x else None, default=None)
    p.add_argument("--mice", type=_opt_csv_list, default=None)

    # Shuffle parameters
    p.add_argument("--n-shuffles", type=int, required=True,
                   help="Number of shuffles to randomly sample from available pool")
    p.add_argument("--shuffle-type", type=str,
                   choices=["time", "spatial", "phase"], default="time")
    p.add_argument("--seed", type=int, default=42,
                   help="Controls reproducible random sampling of shuffle IDs")
    p.add_argument(
        "--different-shuffle-per-trial",
        type=_str2bool,
        default=True,
        help="If True, load caches generated with different shuffles across trials. "
             "If False, load caches generated with one shared shuffle across trials.",
    )

    # Vectorization parameters (must match generation)
    p.add_argument("--p-active", type=int, default=30)
    p.add_argument("--per-trial-thresh", type=_str2bool, default=True)
    p.add_argument("--vectorization-method", type=str, default="Turnover")
    p.add_argument("--clip-frames", type=_opt_int, default=None)
    p.add_argument("--max-trials", type=_opt_int, default=None,
                   help="Used for preflight: shuffles must have been generated with at least this many trials")
    p.add_argument("--grid-subdir", type=str, default="trials_grid")
    p.add_argument("--zz-folder", type=str, default=None)

    # Classification (CNN3D)
    p.add_argument("--batch-size-grid", type=int, default=16)
    p.add_argument("--epochs-cnn3d", type=int, default=40)
    p.add_argument("--lr-cnn3d", type=float, default=0.0005)
    p.add_argument("--weight-decay", type=float, default=0.0001)
    p.add_argument("--early-stop-patience", type=int, default=10)
    p.add_argument("--device", type=str, default="cuda")
    p.add_argument("--num-workers-dl", type=int, default=0)
    p.add_argument("--max-dim", type=int, default=2)

    return p


# ---------------------------------------------------------------------------
# Device
# ---------------------------------------------------------------------------

def _resolve_device(name: str) -> torch.device:
    if name == "cpu":
        return torch.device("cpu")
    if name == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("--device=cuda requested but CUDA is not available")
        return torch.device("cuda")
    if torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


def _set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


# ---------------------------------------------------------------------------
# Preflight validation
# ---------------------------------------------------------------------------

@dataclass
class _FakeState:
    cache_dir: Optional[Path]
    data_root: Path


def _preflight_check(
    eligible_mice: List[str],
    data_root: Path,
    cache_dir: Optional[Path],
    shuffle_type: str,
    method: str,
    p_active: int,
    per_trial_thresh: bool,
    clip_frames: int,
    different_shuffle_per_trial: bool,
    n_shuffles: int,
    max_trials: Optional[int],
    seed: int,
) -> Dict[str, List[int]]:
    """Validate shuffle availability and return sampled IDs per mouse.

    Raises
    ------
    SystemExit
        With a clear, per-mouse error message when any check fails.
    """
    fs = _FakeState(cache_dir=cache_dir, data_root=data_root)
    rng = np.random.default_rng(seed)

    errors: List[str] = []
    sampled: Dict[str, List[int]] = {}

    for mouse_name in eligible_mice:
        mcdir = _resolve_mouse_cache_dir(fs, mouse_name)
        base_stem = build_vectorization_cache_stem(
            mouse_name=mouse_name,
            method=method,
            p_active=p_active,
            per_trial_thresh=per_trial_thresh,
            clip_frames=clip_frames,
        )
        available = _existing_shuffle_ids(
            mcdir,
            base_stem,
            shuffle_type,
            different_shuffle_per_trial,
        )

        # Check 1: Enough shuffles available?
        if len(available) < n_shuffles:
            errors.append(
                f"  {mouse_name}: needs {n_shuffles} shuffles but only "
                f"{len(available)} available (ids={available}). "
                f"Missing: {n_shuffles - len(available)}"
            )
            continue

        # Check 2: Manifest max_trials consistency
        if max_trials is not None:
            manifest = _load_manifest(mcdir, shuffle_type)
            mkey = _manifest_key(
                shuffle_type,
                method,
                p_active,
                per_trial_thresh,
                clip_frames,
                different_shuffle_per_trial,
            )
            entry = manifest.get(mkey, {})
            stored_max = entry.get("max_trials_used", None)
            # None stored means no limit was used during generation (= all trials)
            # A stored value < max_trials means generation used fewer trials than required
            if stored_max is not None and stored_max < max_trials:
                errors.append(
                    f"  {mouse_name}: manifest records max_trials_used={stored_max} "
                    f"but --max-trials={max_trials} requested. "
                    f"Regenerate shuffles with at least max_trials={max_trials}."
                )
                continue

        # Sample N from available (reproducible per mouse: extend seed with mouse hash)
        mouse_seed = int(rng.integers(0, 2**31))
        mouse_rng = np.random.default_rng(mouse_seed)
        chosen = sorted(mouse_rng.choice(available, size=n_shuffles, replace=False).tolist())
        sampled[mouse_name] = chosen

    if errors:
        print("\nPREFLIGHT ERRORS — cannot proceed:", flush=True)
        for e in errors:
            print(e, flush=True)
        sys.exit(1)

    return sampled


# ---------------------------------------------------------------------------
# Within-mouse CV for one shuffle
# ---------------------------------------------------------------------------

def _run_within_mouse_one_shuffle(
    *,
    mouse_name: str,
    shuffle_id: int,
    cache_path: Path,
    data_root: Path,
    meta_root: Path,
    zz_folder: str,
    grid_subdir: str,
    max_trials: Optional[int],
    clip_frames: int,
    device: torch.device,
    epochs_cnn3d: int,
    lr_cnn3d: float,
    batch_size_grid: int,
    weight_decay: float,
    early_stop_patience: int,
    num_workers_dl: int,
    seed: int,
) -> Tuple[Optional[Dict[str, Any]], Optional[Dict[str, Any]]]:
    """Return (result_dict, cm_payload) or (None, None) on skip."""

    # Load cached vectorization
    cached = load_vectorization_cache(cache_path)
    x_vec = np.nan_to_num(np.asarray(
        cached["features"] if "features" in cached else cached["X"]
    ))
    labels = np.asarray(cached["labels"])
    trial_ids_cache = np.asarray(cached.get("trial_ids", np.arange(len(labels))))
    valid_frames_cache = np.asarray(cached.get("valid_frames", np.full(len(labels), clip_frames)))

    if len(np.unique(labels)) < 2:
        print(f"    skipped (only 1 class)", flush=True)
        return None, None

    # Load grid paths for CNN3D
    grid_paths, _, grid_trial_ids, grid_valid_frames = load_labelled_grid_paths(
        data_root, meta_root, mouse_name, grid_subdir=grid_subdir
    )
    grid_idx = {int(tid): i for i, tid in enumerate(grid_trial_ids)}
    # Align trial IDs between cached vec and grids
    common = [tid for tid in trial_ids_cache if int(tid) in grid_idx]
    if not common:
        print(f"    skipped (no overlapping trial IDs with grids)", flush=True)
        return None, None

    vec_idx_map = {int(tid): i for i, tid in enumerate(trial_ids_cache)}
    vec_take = np.array([vec_idx_map[int(tid)] for tid in common], dtype=np.int64)
    grid_take = np.array([grid_idx[int(tid)] for tid in common], dtype=np.int64)

    x_vec_aligned = x_vec[vec_take]
    labels_aligned = labels[vec_take]
    grid_paths_aligned = [grid_paths[i] for i in grid_take]
    gf_aligned = grid_valid_frames[grid_take]

    le = LabelEncoder().fit(labels_aligned)
    y_int = le.transform(labels_aligned)
    class_labels = list(le.classes_)

    n_splits = min(5, int(np.bincount(y_int).min()))
    if n_splits < 2:
        print(f"    skipped (min class count < 2)", flush=True)
        return None, None

    cv = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=seed)
    splits = list(cv.split(np.zeros(len(y_int)), y_int))

    # LogReg
    logreg_metrics, logreg_pred = run_logreg_cv(x_vec_aligned, y_int, splits)

    # 3D-CNN
    grid_dataset = GridTrialDataset(
        grid_paths=grid_paths_aligned,
        y=y_int,
        valid_frames=gf_aligned,
        clip_frames=int(clip_frames),
    )
    cnn3d_metrics, cnn3d_pred = run_nn_cv(
        make_model=lambda: CNN3D(
            n_classes=len(class_labels),
            in_channels=grid_dataset.in_channels,
        ),
        train_dataset_builder=lambda tr_idx, val_idx: (
            Subset(grid_dataset, tr_idx), Subset(grid_dataset, val_idx)
        ),
        y_int=y_int,
        splits=splits,
        epochs=epochs_cnn3d,
        lr=lr_cnn3d,
        batch_size=batch_size_grid,
        patience=early_stop_patience,
        weight_decay=weight_decay,
        device=device,
        num_workers=num_workers_dl,
    )

    best_model = max(
        ["logreg", "cnn3d"],
        key=lambda m: {"logreg": logreg_metrics, "cnn3d": cnn3d_metrics}[m].get("mean_f1", 0),
    )

    result = {
        "shuffle_id": shuffle_id,
        "mouse": mouse_name,
        "n_trials": int(len(y_int)),
        "cv_folds": n_splits,
        "n_features": int(x_vec_aligned.shape[1]),
        "clip_frames": int(clip_frames),
        "class_labels": class_labels,
        "n_classes": len(class_labels),
        "best_model": best_model,
        "models": {
            "logreg": logreg_metrics,
            "cnn3d": cnn3d_metrics,
        },
    }

    model_cms = {
        mk: confusion_matrix(y_int, {"logreg": logreg_pred, "cnn3d": cnn3d_pred}[mk],
                             labels=np.arange(len(class_labels)))
        for mk in ["logreg", "cnn3d"]
    }
    cm_payload = {
        "labels": class_labels,
        "cms": model_cms,
        "best_model": best_model,
    }

    return result, cm_payload


def _save_summary_figures_for_group(
    *,
    group_name: str,
    per_mouse_group: Dict[str, Dict[str, Any]],
    confusion_group: Dict[str, Dict[str, Any]],
    figures_dir: Path,
    method: str,
) -> List[Path]:
    """Save ablation-style summary figures for one result group.

    The group can be one shuffle (e.g. shuffle0003) or an aggregate
    (e.g. avg_across_shuffles).
    """
    model_order = ["logreg", "cnn3d"]
    model_titles = {
        "logreg": "LogReg (vector)",
        "cnn3d": "3D-CNN (grid)",
    }
    colors = {
        "logreg": "#4C72B0",
        "cnn3d": "#DD8452",
    }
    offsets = {
        "logreg": -0.5 * 0.32,
        "cnn3d": 0.5 * 0.32,
    }
    width = 0.32

    mice_order = sorted(per_mouse_group.keys())
    if not mice_order:
        return []

    written: List[Path] = []

    # Figure 1: per-mouse grouped bars (F1 + accuracy)
    x = np.arange(len(mice_order))
    fig, (ax_f1, ax_acc) = plt.subplots(
        2,
        1,
        figsize=(max(9, len(mice_order) * 1.3), 9.0),
        sharex=True,
    )
    for mk in model_order:
        vals_f1 = [float(per_mouse_group[m]["models"][mk]["mean_f1"]) for m in mice_order]
        errs_f1 = [float(per_mouse_group[m]["models"][mk].get("std_f1", 0.0)) for m in mice_order]
        vals_acc = [float(per_mouse_group[m]["models"][mk]["mean_acc"]) for m in mice_order]
        errs_acc = [float(per_mouse_group[m]["models"][mk].get("std_acc", 0.0)) for m in mice_order]

        ax_f1.bar(
            x + offsets[mk],
            vals_f1,
            width,
            yerr=errs_f1,
            capsize=3,
            label=model_titles[mk],
            alpha=0.85,
            color=colors[mk],
        )
        ax_acc.bar(
            x + offsets[mk],
            vals_acc,
            width,
            yerr=errs_acc,
            capsize=3,
            label=model_titles[mk],
            alpha=0.85,
            color=colors[mk],
        )

    ax_f1.set_ylim(0, 1.05)
    ax_f1.set_ylabel("Macro-F1")
    ax_f1.set_title(f"Within-mouse shuffle ablation by mouse ({method}) - {group_name}")
    ax_f1.grid(axis="y", alpha=0.25)
    ax_f1.legend(loc="upper right", ncol=2, fontsize=8)

    ax_acc.set_xticks(x)
    ax_acc.set_xticklabels([_short_mouse_name(m) for m in mice_order], rotation=30, ha="right", fontsize=8)
    ax_acc.set_ylim(0, 1.05)
    ax_acc.set_ylabel("Accuracy")
    ax_acc.set_title(f"Within-mouse shuffle ablation accuracy by mouse ({method}) - {group_name}")
    ax_acc.grid(axis="y", alpha=0.25)

    fig.tight_layout()
    fig1 = figures_dir / f"01_ablation_macro_f1_by_mouse_{group_name}.png"
    fig.savefig(fig1, dpi=300, bbox_inches="tight")
    plt.close(fig)
    written.append(fig1)

    # Figure 2: mean across mice
    fig, axes = plt.subplots(1, 2, figsize=(10, 4.6))
    mean_acc = [np.mean([per_mouse_group[m]["models"][mk]["mean_acc"] for m in mice_order]) for mk in model_order]
    mean_f1 = [np.mean([per_mouse_group[m]["models"][mk]["mean_f1"] for m in mice_order]) for mk in model_order]
    std_acc = [np.std([per_mouse_group[m]["models"][mk]["mean_acc"] for m in mice_order]) for mk in model_order]
    std_f1 = [np.std([per_mouse_group[m]["models"][mk]["mean_f1"] for m in mice_order]) for mk in model_order]

    axes[0].bar(
        np.arange(len(model_order)),
        mean_acc,
        yerr=std_acc,
        capsize=4,
        color=[colors[m] for m in model_order],
        alpha=0.85,
    )
    axes[0].set_xticks(np.arange(len(model_order)))
    axes[0].set_xticklabels([model_titles[m] for m in model_order], rotation=25, ha="right", fontsize=8)
    axes[0].set_ylim(0, 1.05)
    axes[0].set_ylabel("Accuracy")
    axes[0].set_title(f"Mean accuracy across mice ({group_name})")
    axes[0].grid(axis="y", alpha=0.25)

    axes[1].bar(
        np.arange(len(model_order)),
        mean_f1,
        yerr=std_f1,
        capsize=4,
        color=[colors[m] for m in model_order],
        alpha=0.85,
    )
    axes[1].set_xticks(np.arange(len(model_order)))
    axes[1].set_xticklabels([model_titles[m] for m in model_order], rotation=25, ha="right", fontsize=8)
    axes[1].set_ylim(0, 1.05)
    axes[1].set_ylabel("Macro-F1")
    axes[1].set_title(f"Mean macro-F1 across mice ({group_name})")
    axes[1].grid(axis="y", alpha=0.25)

    fig.tight_layout()
    fig2 = figures_dir / f"02_ablation_mean_scores_{group_name}.png"
    fig.savefig(fig2, dpi=300, bbox_inches="tight")
    plt.close(fig)
    written.append(fig2)

    # Figure 3: normalized confusion matrices for all mice (rows) x models (cols)
    n_mice = len(mice_order)
    n_models = len(model_order)
    fig, axes = plt.subplots(
        n_mice,
        n_models,
        figsize=(4.4 * n_models, 3.8 * n_mice),
        squeeze=False,
    )
    for row_idx, mouse_name in enumerate(mice_order):
        payload = confusion_group[mouse_name]
        labels_order = payload["labels"]
        best_model = payload["best_model"]
        for col_idx, mk in enumerate(model_order):
            ax = axes[row_idx][col_idx]
            cm = np.asarray(payload["cms"][mk], dtype=float)
            row_sums = cm.sum(axis=1, keepdims=True)
            cm_norm = np.divide(cm, row_sums, out=np.zeros_like(cm), where=row_sums != 0)
            ConfusionMatrixDisplay(cm_norm, display_labels=labels_order).plot(
                ax=ax,
                cmap="Blues",
                colorbar=False,
                values_format=".2f",
            )
            title = f"{_short_mouse_name(mouse_name)}\\n{model_titles[mk]}"
            if mk == best_model:
                title += " ★"
            ax.set_title(title, fontsize=7)

    fig.suptitle(
        f"Normalized confusion matrices ({group_name}) - all classifiers per mouse (★ = best)",
        fontsize=11,
    )
    fig.tight_layout()
    fig3 = figures_dir / f"03_all_classifier_confusion_matrices_{group_name}.png"
    fig.savefig(fig3, dpi=300, bbox_inches="tight")
    plt.close(fig)
    written.append(fig3)

    return written


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = _build_parser()
    args = parser.parse_args()

    zz_folder = args.zz_folder or _build_zz_folder(args.p_active, args.per_trial_thresh)

    # Discover / validate mice
    discovered = _discover_mice(args.data_root)
    eligible_mice = validate_mice_for_ablation(
        args.mice, args.data_root, args.meta_root, discovered
    )
    if not eligible_mice:
        print("ERROR: No eligible mice found.", file=sys.stderr)
        sys.exit(1)

    # Determine clip frames
    if args.clip_frames is not None:
        global_clip = int(args.clip_frames)
    else:
        print("Pre-scanning valid_frames for global clip ...", flush=True)
        min_list = []
        for mn in eligible_mice:
            try:
                _, _, _, vf = load_labelled_barcodes(
                    args.data_root, args.meta_root, mn, zz_folder, max_trials=args.max_trials
                )
                if len(vf) > 0:
                    min_list.append(int(vf.min()))
            except Exception:
                pass
        if not min_list:
            print("ERROR: Could not determine global clip_frames.", file=sys.stderr)
            sys.exit(1)
        global_clip = min(min_list)
        print(f"  global_clip_frames = {global_clip}", flush=True)

    # ---- PREFLIGHT CHECKS --------------------------------------------------
    print("\nRunning preflight checks ...", flush=True)
    sampled_ids = _preflight_check(
        eligible_mice=eligible_mice,
        data_root=args.data_root,
        cache_dir=args.cache_dir,
        shuffle_type=args.shuffle_type,
        method=args.vectorization_method,
        p_active=args.p_active,
        per_trial_thresh=args.per_trial_thresh,
        clip_frames=global_clip,
        different_shuffle_per_trial=args.different_shuffle_per_trial,
        n_shuffles=args.n_shuffles,
        max_trials=args.max_trials,
        seed=args.seed,
    )
    print(f"Preflight PASSED. Sampled shuffle IDs per mouse:", flush=True)
    for mn, ids in sampled_ids.items():
        print(f"  {mn}: {ids}", flush=True)
    # -------------------------------------------------------------------------

    mode_token = _shuffle_mode_token(args.different_shuffle_per_trial)
    output_dir = args.output_folder / mode_token
    output_dir.mkdir(parents=True, exist_ok=True)
    figures_dir = output_dir / "figures"
    logs_dir = output_dir / "logs"
    figures_dir.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)
    log_path = logs_dir / "run.log"

    device = _resolve_device(args.device)
    _set_seed(args.seed)

    fs = _FakeState(cache_dir=args.cache_dir, data_root=args.data_root)

    with open(log_path, "w", encoding="utf-8") as log_fp, \
         redirect_stdout(log_fp), redirect_stderr(log_fp):

        print("=" * 90)
        print("Within-Mouse Classification on Shuffled Vectorizations")
        print(f"Timestamp: {datetime.now().isoformat(timespec='seconds')}")
        print("=" * 90)
        print(f"  output_folder        : {output_dir}")
        print(f"  shuffle_type         : {args.shuffle_type}")
        print(f"  n_shuffles (sampled) : {args.n_shuffles}")
        print(f"  shuffle_mode         : {mode_token}")
        print(f"  method               : {args.vectorization_method}")
        print(f"  p_active             : {args.p_active}")
        print(f"  clip_frames          : {global_clip}")
        print(f"  device               : {device}")
        print(f"  seed                 : {args.seed}")
        print("\nSampled shuffle IDs:")
        for mn, ids in sampled_ids.items():
            print(f"  {mn}: {ids}")

        # Containers for results
        all_results: Dict[str, Dict[str, Any]] = {}  # {mouse: {shuffle_id: result}}
        all_cms: Dict[str, Dict[str, Any]] = {}

        for mouse_name in eligible_mice:
            print(f"\n{'='*70}")
            print(f"Mouse: {mouse_name}")
            all_results[mouse_name] = {}
            all_cms[mouse_name] = {}

            base_stem = build_vectorization_cache_stem(
                mouse_name=mouse_name,
                method=args.vectorization_method,
                p_active=args.p_active,
                per_trial_thresh=args.per_trial_thresh,
                clip_frames=global_clip,
            )
            mcdir = _resolve_mouse_cache_dir(fs, mouse_name)

            for shuffle_id in sampled_ids[mouse_name]:
                shuffle_stem = _shuffle_cache_stem_with_mode(
                    base_stem,
                    args.shuffle_type,
                    shuffle_id,
                    args.different_shuffle_per_trial,
                )
                cache_path = mcdir / f"{shuffle_stem}.npz"

                print(f"\n  [shuffle {shuffle_id}]", end=" ", flush=True)
                try:
                    result, cm_payload = _run_within_mouse_one_shuffle(
                        mouse_name=mouse_name,
                        shuffle_id=shuffle_id,
                        cache_path=cache_path,
                        data_root=args.data_root,
                        meta_root=args.meta_root,
                        zz_folder=zz_folder,
                        grid_subdir=args.grid_subdir,
                        max_trials=args.max_trials,
                        clip_frames=global_clip,
                        device=device,
                        epochs_cnn3d=args.epochs_cnn3d,
                        lr_cnn3d=args.lr_cnn3d,
                        batch_size_grid=args.batch_size_grid,
                        weight_decay=args.weight_decay,
                        early_stop_patience=args.early_stop_patience,
                        num_workers_dl=args.num_workers_dl,
                        seed=args.seed,
                    )
                    if result is not None:
                        all_results[mouse_name][shuffle_id] = result
                        all_cms[mouse_name][shuffle_id] = cm_payload
                        best = result["best_model"]
                        f1 = result["models"][best].get("mean_f1", 0)
                        print(f"ok (best={best}:{f1:.3f})")
                except Exception as exc:
                    print(f"FAILED: {exc}")
                    traceback.print_exc()

                gc.collect()

        # ---- Save figures ---------------------------------------------------
        print("\nSaving ablation-style figures (per shuffle + average across shuffles) ...", flush=True)
        written_figures: List[Path] = []

        # Build per-shuffle grouped views: {shuffle_id -> per_mouse_result/payload}
        shuffle_ids_present = sorted({sid for per_mouse in all_results.values() for sid in per_mouse.keys()})
        for shuffle_id in shuffle_ids_present:
            per_mouse_group: Dict[str, Dict[str, Any]] = {}
            confusion_group: Dict[str, Dict[str, Any]] = {}
            for mouse_name in eligible_mice:
                if shuffle_id in all_results.get(mouse_name, {}):
                    per_mouse_group[mouse_name] = all_results[mouse_name][shuffle_id]
                if shuffle_id in all_cms.get(mouse_name, {}):
                    confusion_group[mouse_name] = all_cms[mouse_name][shuffle_id]

            if per_mouse_group and confusion_group:
                gname = f"shuffle{int(shuffle_id):04d}"
                written_figures.extend(
                    _save_summary_figures_for_group(
                        group_name=gname,
                        per_mouse_group=per_mouse_group,
                        confusion_group=confusion_group,
                        figures_dir=figures_dir,
                        method=args.vectorization_method,
                    )
                )

        # Average across shuffles: per-mouse model metrics averaged over available shuffles,
        # and confusion matrices averaged element-wise over shuffles.
        avg_per_mouse: Dict[str, Dict[str, Any]] = {}
        avg_cms: Dict[str, Dict[str, Any]] = {}
        for mouse_name in eligible_mice:
            shuf_results = all_results.get(mouse_name, {})
            shuf_cms = all_cms.get(mouse_name, {})
            if not shuf_results or not shuf_cms:
                continue

            shuffle_keys = sorted(set(shuf_results.keys()) & set(shuf_cms.keys()))
            if not shuffle_keys:
                continue

            logreg_acc = [float(shuf_results[s]["models"]["logreg"].get("mean_acc", shuf_results[s]["models"]["logreg"].get("accuracy", 0.0))) for s in shuffle_keys]
            logreg_f1 = [float(shuf_results[s]["models"]["logreg"].get("mean_f1", shuf_results[s]["models"]["logreg"].get("macro_f1", 0.0))) for s in shuffle_keys]
            cnn3d_acc = [float(shuf_results[s]["models"]["cnn3d"].get("mean_acc", shuf_results[s]["models"]["cnn3d"].get("accuracy", 0.0))) for s in shuffle_keys]
            cnn3d_f1 = [float(shuf_results[s]["models"]["cnn3d"].get("mean_f1", shuf_results[s]["models"]["cnn3d"].get("macro_f1", 0.0))) for s in shuffle_keys]

            avg_models = {
                "logreg": {
                    "mean_acc": float(np.mean(logreg_acc)),
                    "std_acc": float(np.std(logreg_acc)),
                    "mean_f1": float(np.mean(logreg_f1)),
                    "std_f1": float(np.std(logreg_f1)),
                },
                "cnn3d": {
                    "mean_acc": float(np.mean(cnn3d_acc)),
                    "std_acc": float(np.std(cnn3d_acc)),
                    "mean_f1": float(np.mean(cnn3d_f1)),
                    "std_f1": float(np.std(cnn3d_f1)),
                },
            }
            best_model = max(["logreg", "cnn3d"], key=lambda m: avg_models[m]["mean_f1"])

            first_row = shuf_results[shuffle_keys[0]]
            avg_per_mouse[mouse_name] = {
                "shuffle_id": "avg",
                "mouse": mouse_name,
                "n_trials": int(first_row["n_trials"]),
                "cv_folds": int(first_row["cv_folds"]),
                "n_features": int(first_row["n_features"]),
                "clip_frames": int(first_row["clip_frames"]),
                "class_labels": list(first_row["class_labels"]),
                "n_classes": int(first_row["n_classes"]),
                "best_model": best_model,
                "models": avg_models,
            }

            labels_order = list(shuf_cms[shuffle_keys[0]]["labels"])
            cm_logreg_stack = np.stack([np.asarray(shuf_cms[s]["cms"]["logreg"], dtype=float) for s in shuffle_keys], axis=0)
            cm_cnn3d_stack = np.stack([np.asarray(shuf_cms[s]["cms"]["cnn3d"], dtype=float) for s in shuffle_keys], axis=0)
            avg_cms[mouse_name] = {
                "labels": labels_order,
                "cms": {
                    "logreg": np.mean(cm_logreg_stack, axis=0),
                    "cnn3d": np.mean(cm_cnn3d_stack, axis=0),
                },
                "best_model": best_model,
            }

        if avg_per_mouse and avg_cms:
            written_figures.extend(
                _save_summary_figures_for_group(
                    group_name="avg_across_shuffles",
                    per_mouse_group=avg_per_mouse,
                    confusion_group=avg_cms,
                    figures_dir=figures_dir,
                    method=args.vectorization_method,
                )
            )

        # ---- Save JSON / CSV ------------------------------------------------
        json_path = output_dir / "within_mouse_ablation_shuffle_metrics.json"
        csv_path = output_dir / "within_mouse_ablation_shuffle_metrics.csv"

        payload_json = {
            "method": args.vectorization_method,
            "p_active": args.p_active,
            "shuffle_type": args.shuffle_type,
            "different_shuffle_per_trial": args.different_shuffle_per_trial,
            "shuffle_mode": mode_token,
            "n_shuffles_requested": args.n_shuffles,
            "seed": args.seed,
            "eligible_mice": eligible_mice,
            "sampled_shuffle_ids": sampled_ids,
            "per_mouse": all_results,
            "figures": [str(p) for p in written_figures],
        }
        with open(json_path, "w", encoding="utf-8") as fp:
            json.dump(payload_json, fp, indent=2)
        print(f"Wrote JSON: {json_path}")

        with open(csv_path, "w", encoding="utf-8", newline="") as fp:
            writer = csv.writer(fp)
            writer.writerow([
                "shuffle_mode",
                "different_shuffle_per_trial",
                "mouse", "shuffle_id", "model",
                "n_trials", "cv_folds",
                "mean_acc", "std_acc", "mean_f1", "std_f1",
                "best_model",
            ])
            for mouse_name, shuf_results in all_results.items():
                for shuffle_id, row in shuf_results.items():
                    for mk in ["logreg", "cnn3d"]:
                        mr = row["models"][mk]
                        writer.writerow([
                            mode_token,
                            args.different_shuffle_per_trial,
                            mouse_name,
                            shuffle_id,
                            mk,
                            row["n_trials"],
                            row["cv_folds"],
                            mr.get("mean_acc", mr.get("accuracy")),
                            mr.get("std_acc", 0),
                            mr.get("mean_f1", mr.get("macro_f1")),
                            mr.get("std_f1", 0),
                            row["best_model"],
                        ])
        print(f"Wrote CSV : {csv_path}")

        print("\n" + "=" * 90)
        print("SUCCESS")
        print("=" * 90)

    print(f"Done. Results: {output_dir}", flush=True)


if __name__ == "__main__":
    main()
