#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2026 Ana Flo <anaflom@gmail.com>
#
# SPDX-License-Identifier: BSD-3-Clause

"""Cross-mouse (LOMO) classification on pre-cached shuffled zigzag vectorizations.

Requires shuffles to be pre-generated by generate_trials_ablation_shuffle.py.

Preflight checks (all run before any training):
  1. Each mouse has at least --n-shuffles available randomizations for the
     requested shuffle-type / configuration.  Fails with an explicit message
     listing which mice have too few and how many are missing.
  2. Shuffle manifests indicate generation used at least --max-trials.
     Fails if any mouse was generated with fewer trials than requested.
  3. Randomly samples exactly --n-shuffles IDs from each mouse's available
     pool (seeded by --seed for reproducibility).  Uses the intersection of
     available IDs across ALL mice so that each shuffle-round is coherent.

Outputs per run folder:
  cross_mouse_ablation_shuffle_metrics.json
  cross_mouse_ablation_shuffle_metrics.csv
  figures/   (confusion matrices)
  logs/run.log

Usage examples
--------------
  python classify_trials_cross_mouse_ablation_shuffle.py \\
         --output-folder results/ablation_shuffle/time/p30-per-trial/cross_run1 \\
         --n-shuffles 5 --shuffle-type time

  python classify_trials_cross_mouse_ablation_shuffle.py \\
         --output-folder results/ablation_shuffle/time/p30-per-trial/cross_run2 \\
         --n-shuffles 10 --shuffle-type time --max-trials 200 --seed 0
"""

from __future__ import annotations

import argparse
import csv
import gc
import json
import random
import sys
import traceback
from contextlib import redirect_stderr, redirect_stdout
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from torch.utils.data import Subset

from classification_models import (
    CNN1D,
    CNN3D,
    GridTrialDataset,
    MLP,
    VectorDataset,
    infer_cnn1d_shape,
    train_eval_logreg,
    train_eval_nn,
)

MODEL_CHOICES = ["logreg", "mlp", "cnn1d", "cnn3d_raw", "cnn3d_norm"]
DEFAULT_MODELS = ["logreg", "mlp", "cnn1d", "cnn3d_raw", "cnn3d_norm"]
MODEL_TITLES = {
    "logreg": "LogReg (vector)",
    "mlp": "MLP (vector)",
    "cnn1d": "1D-CNN (vector)",
    "cnn3d_raw": "3D-CNN (raw grid)",
    "cnn3d_norm": "3D-CNN (normalized grid)",
}
MODEL_COLORS = {
    "logreg": "#4C72B0",
    "mlp": "#55A868",
    "cnn1d": "#C44E52",
    "cnn3d_raw": "#DD8452",
    "cnn3d_norm": "#937860",
}


def _resolve_models(models: Optional[List[str]]) -> List[str]:
    chosen = DEFAULT_MODELS if models is None else [m.strip() for m in models if str(m).strip()]
    if not chosen:
        raise ValueError("--models resolved to an empty list")
    unknown = sorted({m for m in chosen if m not in MODEL_CHOICES})
    if unknown:
        raise ValueError(f"Unknown model(s) in --models: {unknown}. Allowed: {MODEL_CHOICES}")
    deduped: List[str] = []
    for mk in chosen:
        if mk not in deduped:
            deduped.append(mk)
    return deduped


def _grid_mode_label(model_order: List[str]) -> str:
    parts: List[str] = []
    if "cnn3d_raw" in model_order:
        parts.append("raw-grid")
    if "cnn3d_norm" in model_order:
        parts.append("trial-l1-normalized-grid")
    return "+".join(parts) if parts else "no-grid-model"


from shuffle_utils import validate_mice_for_ablation
from utils import (
    _build_zz_folder,
    _discover_mice,
    _opt_csv_list,
    _opt_int,
    _resolve_mouse_cache_dir,
    _short_mouse_name,
    _str2bool,
    build_vectorization_cache_stem,
    load_labelled_barcodes,
    load_shuffled_grid_cache_paths,
    load_vectorization_cache,
)


# ---------------------------------------------------------------------------
# Cache index helpers (mirrors generate / within scripts)
# ---------------------------------------------------------------------------

def _shuffle_cache_stem(base_stem: str, shuffle_type: str) -> str:
    return f"{base_stem}_{shuffle_type}"


def _shuffle_mode_token(different_shuffle_per_trial: bool) -> str:
    return "different" if different_shuffle_per_trial else "same"


def _shuffle_cache_stem_with_mode(
    base_stem: str,
    shuffle_type: str,
    shuffle_id: int,
    different_shuffle_per_trial: bool,
) -> str:
    mode_token = _shuffle_mode_token(different_shuffle_per_trial)
    return f"{_shuffle_cache_stem(base_stem, shuffle_type)}_{mode_token}_shuffle{shuffle_id:04d}"


def _existing_shuffle_ids(
    cache_dir: Path,
    base_stem: str,
    shuffle_type: str,
    different_shuffle_per_trial: bool,
) -> List[int]:
    ids = []
    stem_prefix = _shuffle_cache_stem(base_stem, shuffle_type)
    mode_token = _shuffle_mode_token(different_shuffle_per_trial)
    for p in cache_dir.glob(f"{stem_prefix}_{mode_token}_shuffle*.npz"):
        stem = p.stem
        try:
            idx = int(stem.rsplit("shuffle", 1)[1])
            ids.append(idx)
        except (IndexError, ValueError):
            pass
    return sorted(ids)


MANIFEST_FILENAME = "shuffle_manifest.json"


def _latest_manifest_path(cache_dir: Path, shuffle_type: str) -> Optional[Path]:
    legacy = cache_dir / MANIFEST_FILENAME
    if legacy.exists():
        return legacy
    return None


def _load_manifest(cache_dir: Path, shuffle_type: str) -> Dict[str, Any]:
    mp = _latest_manifest_path(cache_dir, shuffle_type)
    if mp is not None:
        with open(mp, encoding="utf-8") as fp:
            return json.load(fp)
    return {}


def _manifest_key(
    shuffle_type: str,
    method: str,
    p_active: int,
    per_trial_thresh: bool,
    clip_frames: int,
    different_shuffle_per_trial: bool,
) -> str:
    pt = "pertrial1" if per_trial_thresh else "pertrial0"
    mode_token = _shuffle_mode_token(different_shuffle_per_trial)
    return f"{shuffle_type}__{method}__{p_active}__{pt}__clip{clip_frames}__shufflemode-{mode_token}"


# ---------------------------------------------------------------------------
# Fake state dataclass for _resolve_mouse_cache_dir
# ---------------------------------------------------------------------------

@dataclass
class _FakeState:
    cache_dir: Optional[Path]
    data_root: Path


# ---------------------------------------------------------------------------
# Argument parser
# ---------------------------------------------------------------------------

def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description="Cross-mouse LOMO classification on pre-cached shuffled vectorizations"
    )
    p.add_argument("--output-folder", type=Path, required=True)
    p.add_argument("--data-root", type=Path, required=True)
    p.add_argument("--meta-root", type=Path, required=True)
    p.add_argument("--cache-dir", type=lambda x: Path(x) if x else None, default=None)
    p.add_argument("--mice", type=_opt_csv_list, default=None)
    p.add_argument(
        "--models",
        type=_opt_csv_list,
        default=None,
        help=(
            "Comma-separated models to run. Allowed: "
            f"{','.join(MODEL_CHOICES)}. Default: {','.join(DEFAULT_MODELS)}"
        ),
    )

    # Shuffle parameters
    p.add_argument("--n-shuffles", type=int, required=True,
                   help="Number of shuffles to randomly sample from available pool")
    p.add_argument("--shuffle-type", type=str,
                   choices=["time", "spatial", "phase"], default="time")
    p.add_argument("--seed", type=int, default=42,
                   help="Controls reproducible random sampling of shuffle IDs")
    p.add_argument(
        "--different-shuffle-per-trial",
        type=_str2bool,
        default=True,
        help="If True, load caches generated with different shuffles across trials. "
             "If False, load caches generated with one shared shuffle across trials.",
    )

    # Vectorization parameters (must match generation)
    p.add_argument("--p-active", type=int, default=30)
    p.add_argument("--per-trial-thresh", type=_str2bool, default=True)
    p.add_argument("--vectorization-method", type=str, default="Turnover")
    p.add_argument("--clip-frames", type=_opt_int, default=None)
    p.add_argument("--max-trials", type=_opt_int, default=None,
                   help="Used for preflight: shuffles must have been generated with at least this many trials")
    p.add_argument("--grid-subdir", type=str, default="trials_grid")
    p.add_argument("--zz-folder", type=str, default=None)
    p.add_argument("--max-dim", type=int, default=2)

    # Classification
    p.add_argument("--batch-size-vec", type=int, default=64)
    p.add_argument("--batch-size-grid", type=int, default=16)
    p.add_argument("--epochs-mlp", type=int, default=60)
    p.add_argument("--epochs-cnn1d", type=int, default=60)
    p.add_argument("--epochs-cnn3d", type=int, default=40)
    p.add_argument("--lr-vec", type=float, default=1e-3)
    p.add_argument("--lr-cnn3d", type=float, default=0.0005)
    p.add_argument("--weight-decay", type=float, default=0.0001)
    p.add_argument("--early-stop-patience", type=int, default=10)
    p.add_argument("--device", type=str, default="cuda")
    p.add_argument("--num-workers-dl", type=int, default=0)

    return p


# ---------------------------------------------------------------------------
# Device
# ---------------------------------------------------------------------------

def _resolve_device(name: str) -> torch.device:
    if name == "cpu":
        return torch.device("cpu")
    if name == "cuda":
        if not torch.cuda.is_available():
            raise RuntimeError("--device=cuda requested but CUDA is not available")
        return torch.device("cuda")
    if torch.cuda.is_available():
        return torch.device("cuda")
    return torch.device("cpu")


def _set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def _canonicalize_holdout_metrics(metrics: Dict[str, Any]) -> Dict[str, Any]:
    normalized = dict(metrics)
    if "accuracy" not in normalized and "mean_acc" in normalized:
        normalized["accuracy"] = normalized["mean_acc"]
    if "macro_f1" not in normalized and "mean_f1" in normalized:
        normalized["macro_f1"] = normalized["mean_f1"]
    return normalized


# ---------------------------------------------------------------------------
# Preflight validation — cross-mouse uses intersection of available IDs
# ---------------------------------------------------------------------------

def _preflight_check(
    eligible_mice: List[str],
    data_root: Path,
    cache_dir: Optional[Path],
    shuffle_type: str,
    method: str,
    p_active: int,
    per_trial_thresh: bool,
    clip_frames: int,
    different_shuffle_per_trial: bool,
    n_shuffles: int,
    max_trials: Optional[int],
    seed: int,
) -> List[int]:
    """Validate and return the sampled shuffle IDs (same set used for all mice).

    For cross-mouse coherence we take the intersection of available IDs across
    all mice, then randomly sample N from that intersection.

    Raises
    ------
    SystemExit
        With a clear per-mouse error message when any check fails.
    """
    fs = _FakeState(cache_dir=cache_dir, data_root=data_root)

    errors: List[str] = []
    per_mouse_available: Dict[str, List[int]] = {}

    for mouse_name in eligible_mice:
        mcdir = _resolve_mouse_cache_dir(fs, mouse_name)
        base_stem = build_vectorization_cache_stem(
            mouse_name=mouse_name,
            method=method,
            p_active=p_active,
            per_trial_thresh=per_trial_thresh,
            clip_frames=clip_frames,
        )
        available = _existing_shuffle_ids(
            mcdir,
            base_stem,
            shuffle_type,
            different_shuffle_per_trial,
        )

        # Check 1: Enough shuffles?
        if len(available) < n_shuffles:
            errors.append(
                f"  {mouse_name}: needs {n_shuffles} shuffles but only "
                f"{len(available)} available (ids={available}). "
                f"Missing: {n_shuffles - len(available)}"
            )
            continue

        # Check 2: Manifest max_trials consistency
        if max_trials is not None:
            manifest = _load_manifest(mcdir, shuffle_type)
            mkey = _manifest_key(
                shuffle_type,
                method,
                p_active,
                per_trial_thresh,
                clip_frames,
                different_shuffle_per_trial,
            )
            entry = manifest.get(mkey, {})
            stored_max = entry.get("max_trials_used", None)
            if stored_max is not None and stored_max < max_trials:
                errors.append(
                    f"  {mouse_name}: manifest records max_trials_used={stored_max} "
                    f"but --max-trials={max_trials} requested. "
                    f"Regenerate shuffles with at least max_trials={max_trials}."
                )
                continue

        per_mouse_available[mouse_name] = available

    if errors:
        print("\nPREFLIGHT ERRORS — cannot proceed:", flush=True)
        for e in errors:
            print(e, flush=True)
        sys.exit(1)

    # Compute intersection across all eligible mice
    id_sets = [set(ids) for ids in per_mouse_available.values()]
    common_ids = sorted(set.intersection(*id_sets) if id_sets else set())

    if len(common_ids) < n_shuffles:
        print(
            f"\nPREFLIGHT ERROR: only {len(common_ids)} shuffle IDs are present for ALL "
            f"mice (intersection={common_ids}), but {n_shuffles} requested.",
            flush=True,
        )
        print("Per-mouse availability:", flush=True)
        for mn, ids in per_mouse_available.items():
            print(f"  {mn}: {ids}", flush=True)
        sys.exit(1)

    rng = np.random.default_rng(seed)
    sampled = sorted(rng.choice(common_ids, size=n_shuffles, replace=False).tolist())
    return sampled


# ---------------------------------------------------------------------------
# Load mouse data from cache for a given shuffle ID
# ---------------------------------------------------------------------------

def _load_mouse_shuffle_data(
    *,
    mouse_name: str,
    shuffle_id: int,
    cache_path: Path,
    clip_frames: int,
) -> Optional[Dict[str, Any]]:
    """Load cached shuffled vectorization + shuffled grid paths for one mouse/shuffle.

    Returns a dict with the same field names as ``_load_mouse_data`` in the
    non-shuffle script so that the same 4-model training block can be reused.
    Raises ``FileNotFoundError`` if the shuffled grid cache is missing
    (run ``generate_trials_ablation_shuffle.py`` to regenerate).
    """
    cached = load_vectorization_cache(cache_path)
    x_vec = np.nan_to_num(np.asarray(
        cached["features"] if "features" in cached else cached["X"]
    ))
    labels = np.asarray(cached["labels"])
    trial_ids_cache = np.asarray(cached.get("trial_ids", np.arange(len(labels))))
    valid_frames_cache = np.asarray(cached.get("valid_frames", np.full(len(labels), clip_frames)))

    if len(np.unique(labels)) < 2:
        return None

    # Load shuffled grid paths saved by generate_trials_ablation_shuffle.py
    grid_paths = load_shuffled_grid_cache_paths(cache_path, trial_ids_cache.tolist())

    first_shape = np.load(grid_paths[0], mmap_mode="r").shape
    in_channels = int(first_shape[2])

    return {
        "mouse": mouse_name,
        "x_vec": x_vec,
        "labels": labels,
        "grid_paths": grid_paths,
        "grid_frames": valid_frames_cache,
        "in_channels": in_channels,
        "cache_path": str(cache_path),
        "vec_source": "shuffle_cache",
        "n_trials": int(len(labels)),
    }


# ---------------------------------------------------------------------------
# Cross-mouse LOMO for one shuffle ID
# ---------------------------------------------------------------------------

def _run_cross_mouse_one_shuffle(
    *,
    shuffle_id: int,
    eligible_mice: List[str],
    mouse_data: Dict[str, Optional[Dict[str, Any]]],
    clip_frames: int,
    model_order: List[str],
    device: torch.device,
    epochs_mlp: int,
    epochs_cnn1d: int,
    epochs_cnn3d: int,
    lr_vec: float,
    lr_cnn3d: float,
    batch_size_vec: int,
    batch_size_grid: int,
    weight_decay: float,
    early_stop_patience: int,
    num_workers_dl: int,
    seed: int,
) -> Tuple[Dict[str, Any], Dict[str, Any]]:
    """Run LOMO for one shuffle_id across all eligible mice."""
    per_fold: Dict[str, Any] = {}
    cm_payload: Dict[str, Any] = {}

    available_mice = [m for m in eligible_mice if mouse_data.get(m) is not None]
    if len(available_mice) < 2:
        print(f"    skipped (need >= 2 mice with data, got {len(available_mice)})", flush=True)
        return per_fold, cm_payload

    for test_mouse in available_mice:
        candidate_train_mice = [m for m in available_mice if m != test_mouse]
        print(
            f"\n    test={test_mouse[-20:]} train_pool={len(candidate_train_mice)} ...",
            end=" ",
            flush=True,
        )

        try:
            test_data = mouse_data[test_mouse]
            test_labels_set = set(np.unique(test_data["labels"]).tolist())
            train_label_union: set = set()
            for mn in candidate_train_mice:
                train_label_union.update(np.unique(mouse_data[mn]["labels"]).tolist())

            shared_labels = sorted(test_labels_set & train_label_union)
            if len(shared_labels) < 2:
                print(f"skipped (shared_labels={len(shared_labels)} < 2)")
                continue

            encoder = LabelEncoder().fit(shared_labels)

            # Test set
            test_mask = np.isin(test_data["labels"], shared_labels)
            if not np.any(test_mask):
                print("skipped (no test samples)")
                continue
            test_x_vec = np.asarray(test_data["x_vec"][test_mask], dtype=np.float64)
            test_y = encoder.transform(test_data["labels"][test_mask])
            test_grid_paths = [test_data["grid_paths"][i] for i in np.where(test_mask)[0]]
            test_grid_frames = np.asarray(test_data["grid_frames"][test_mask], dtype=np.int64)

            # Train set
            train_x_parts: List[np.ndarray] = []
            train_y_parts: List[np.ndarray] = []
            train_grid_paths: List[Any] = []
            train_grid_frames_list: List[int] = []
            active_train_mice: List[str] = []

            for mn in candidate_train_mice:
                td = mouse_data[mn]
                mask = np.isin(td["labels"], shared_labels)
                if not np.any(mask):
                    continue
                active_train_mice.append(mn)
                train_x_parts.append(np.asarray(td["x_vec"][mask], dtype=np.float64))
                train_y_parts.append(encoder.transform(td["labels"][mask]))
                idxs = np.where(mask)[0]
                train_grid_paths.extend([td["grid_paths"][i] for i in idxs])
                train_grid_frames_list.extend(
                    np.asarray(td["grid_frames"][mask], dtype=np.int64).tolist()
                )

            if not train_x_parts:
                print("skipped (no training samples)")
                continue

            train_x_vec = np.concatenate(train_x_parts, axis=0)
            train_y = np.concatenate(train_y_parts, axis=0)
            train_grid_frames = np.asarray(train_grid_frames_list, dtype=np.int64)

            if len(np.unique(train_y)) < 2 or len(np.unique(test_y)) < 2:
                print("skipped (collapsed class)")
                continue

            # Scale vector features (same as non-shuffle script)
            from sklearn.preprocessing import StandardScaler
            scaler = StandardScaler().fit(train_x_vec)
            x_train_scaled = scaler.transform(train_x_vec)
            x_test_scaled = scaler.transform(test_x_vec)
            cnn1d_channels, cnn1d_seq_len = infer_cnn1d_shape(train_x_vec.shape[1], clip_frames)

            model_metrics: Dict[str, Dict[str, float]] = {}
            model_preds: Dict[str, np.ndarray] = {}

            if "logreg" in model_order:
                logreg_metrics, logreg_pred = train_eval_logreg(
                    x_train_scaled, train_y, x_test_scaled, test_y
                )
                model_metrics["logreg"] = logreg_metrics
                model_preds["logreg"] = logreg_pred

            if "mlp" in model_order:
                mlp_metrics, mlp_pred = train_eval_nn(
                    make_model=lambda: MLP(
                        n_classes=len(shared_labels), input_dim=train_x_vec.shape[1]
                    ),
                    train_ds=VectorDataset(x_train_scaled, train_y),
                    y_train=train_y,
                    test_ds=VectorDataset(x_test_scaled, test_y),
                    test_y=test_y,
                    epochs=epochs_mlp,
                    lr=lr_vec,
                    batch_size=batch_size_vec,
                    patience=early_stop_patience,
                    weight_decay=weight_decay,
                    device=device,
                    num_workers=num_workers_dl,
                    seed=seed,
                )
                model_metrics["mlp"] = mlp_metrics
                model_preds["mlp"] = mlp_pred

            if "cnn1d" in model_order:
                cnn1d_metrics, cnn1d_pred = train_eval_nn(
                    make_model=lambda: CNN1D(
                        n_classes=len(shared_labels),
                        in_channels=cnn1d_channels,
                        seq_len=cnn1d_seq_len,
                    ),
                    train_ds=VectorDataset(x_train_scaled, train_y),
                    y_train=train_y,
                    test_ds=VectorDataset(x_test_scaled, test_y),
                    test_y=test_y,
                    epochs=epochs_cnn1d,
                    lr=lr_vec,
                    batch_size=batch_size_vec,
                    patience=early_stop_patience,
                    weight_decay=weight_decay,
                    device=device,
                    num_workers=num_workers_dl,
                    seed=seed,
                )
                model_metrics["cnn1d"] = cnn1d_metrics
                model_preds["cnn1d"] = cnn1d_pred

            if "cnn3d_raw" in model_order:
                train_grid_ds_raw = GridTrialDataset(
                    grid_paths=train_grid_paths,
                    y=train_y,
                    valid_frames=train_grid_frames,
                    clip_frames=int(clip_frames),
                    normalize_by_trial=False,
                )
                test_grid_ds_raw = GridTrialDataset(
                    grid_paths=test_grid_paths,
                    y=test_y,
                    valid_frames=test_grid_frames,
                    clip_frames=int(clip_frames),
                    normalize_by_trial=False,
                )
                cnn3d_raw_metrics, cnn3d_raw_pred = train_eval_nn(
                    make_model=lambda: CNN3D(
                        n_classes=len(shared_labels),
                        in_channels=test_data["in_channels"],
                    ),
                    train_ds=train_grid_ds_raw,
                    y_train=train_y,
                    test_ds=test_grid_ds_raw,
                    test_y=test_y,
                    epochs=epochs_cnn3d,
                    lr=lr_cnn3d,
                    batch_size=batch_size_grid,
                    patience=early_stop_patience,
                    weight_decay=weight_decay,
                    device=device,
                    num_workers=num_workers_dl,
                    seed=seed,
                )
                model_metrics["cnn3d_raw"] = cnn3d_raw_metrics
                model_preds["cnn3d_raw"] = cnn3d_raw_pred

            if "cnn3d_norm" in model_order:
                train_grid_ds_norm = GridTrialDataset(
                    grid_paths=train_grid_paths,
                    y=train_y,
                    valid_frames=train_grid_frames,
                    clip_frames=int(clip_frames),
                    normalize_by_trial=True,
                )
                test_grid_ds_norm = GridTrialDataset(
                    grid_paths=test_grid_paths,
                    y=test_y,
                    valid_frames=test_grid_frames,
                    clip_frames=int(clip_frames),
                    normalize_by_trial=True,
                )
                cnn3d_norm_metrics, cnn3d_norm_pred = train_eval_nn(
                    make_model=lambda: CNN3D(
                        n_classes=len(shared_labels),
                        in_channels=test_data["in_channels"],
                    ),
                    train_ds=train_grid_ds_norm,
                    y_train=train_y,
                    test_ds=test_grid_ds_norm,
                    test_y=test_y,
                    epochs=epochs_cnn3d,
                    lr=lr_cnn3d,
                    batch_size=batch_size_grid,
                    patience=early_stop_patience,
                    weight_decay=weight_decay,
                    device=device,
                    num_workers=num_workers_dl,
                    seed=seed,
                )
                model_metrics["cnn3d_norm"] = cnn3d_norm_metrics
                model_preds["cnn3d_norm"] = cnn3d_norm_pred

            if not model_metrics:
                print("skipped (no models executed)")
                continue

            best_model = max(model_metrics.keys(), key=lambda mk: model_metrics[mk]["macro_f1"])

            per_fold[test_mouse] = {
                "shuffle_id": shuffle_id,
                "test_mouse": test_mouse,
                "train_mice": active_train_mice,
                "n_train_mice": len(active_train_mice),
                "n_train_trials": int(len(train_y)),
                "n_test_trials": int(len(test_y)),
                "n_features": int(train_x_vec.shape[1]),
                "clip_frames": int(clip_frames),
                "shared_labels": shared_labels,
                "n_classes": int(len(shared_labels)),
                "cnn1d_channels": int(cnn1d_channels),
                "cnn1d_seq_len": int(cnn1d_seq_len),
                "best_model": best_model,
                "models": model_metrics,
            }

            model_cms = {
                mk: confusion_matrix(
                    test_y,
                    model_preds[mk],
                    labels=np.arange(len(shared_labels)),
                )
                for mk in model_metrics.keys()
            }
            cm_payload[test_mouse] = {
                "labels": shared_labels,
                "cms": model_cms,
                "best_model": best_model,
            }

            f1 = max(model_metrics[mk]["macro_f1"] for mk in model_metrics.keys())
            print(f"ok (best={best_model}, f1={f1:.3f})")

        except Exception as exc:
            print(f"FAILED: {exc}")
            traceback.print_exc()

    return per_fold, cm_payload


def _save_lomo_summary_figures_for_group(
    *,
    group_name: str,
    per_fold_group: Dict[str, Dict[str, Any]],
    confusion_group: Dict[str, Dict[str, Any]],
    figures_dir: Path,
    method: str,
    grid_mode_label: str,
    model_order: List[str],
) -> List[Path]:
    """Save cross-mouse LOMO figure set for one group."""
    model_titles = {mk: MODEL_TITLES[mk] for mk in model_order}
    colors = {mk: MODEL_COLORS[mk] for mk in model_order}
    n_models = len(model_order)
    width = min(0.8 / max(n_models, 1), 0.22)
    offsets = {
        mk: (idx - (n_models - 1) / 2.0) * width
        for idx, mk in enumerate(model_order)
    }

    fold_order = sorted(per_fold_group.keys())
    if not fold_order:
        return []

    written: List[Path] = []

    # Figure 1: per-test-mouse bars
    fig, (ax_f1, ax_acc) = plt.subplots(
        2,
        1,
        figsize=(max(9, len(fold_order) * 1.3), 9.0),
        sharex=True,
    )
    x = np.arange(len(fold_order))

    for mk in model_order:
        vals_f1 = [float(per_fold_group[m]["models"][mk]["macro_f1"]) for m in fold_order]
        vals_acc = [float(per_fold_group[m]["models"][mk]["accuracy"]) for m in fold_order]
        ax_f1.bar(x + offsets[mk], vals_f1, width, label=model_titles[mk], alpha=0.85, color=colors[mk])
        ax_acc.bar(x + offsets[mk], vals_acc, width, label=model_titles[mk], alpha=0.85, color=colors[mk])

    ax_f1.set_ylim(0, 1.05)
    ax_f1.set_ylabel("Macro-F1")
    ax_f1.set_title(
        f"Cross-mouse LOMO macro-F1 by test mouse ({method}, {grid_mode_label}) - {group_name}"
    )
    ax_f1.grid(axis="y", alpha=0.25)
    ax_f1.legend(loc="upper right", ncol=min(3, n_models), fontsize=8)

    ax_acc.set_xticks(x)
    ax_acc.set_xticklabels([_short_mouse_name(m) for m in fold_order], rotation=30, ha="right", fontsize=8)
    ax_acc.set_ylim(0, 1.05)
    ax_acc.set_ylabel("Accuracy")
    ax_acc.set_title(
        f"Cross-mouse LOMO accuracy by test mouse ({method}, {grid_mode_label}) - {group_name}"
    )
    ax_acc.grid(axis="y", alpha=0.25)

    fig.tight_layout()
    fig1 = figures_dir / f"01_lomo_macro_f1_by_test_mouse_{group_name}.png"
    fig.savefig(fig1, dpi=300, bbox_inches="tight")
    plt.close(fig)
    written.append(fig1)

    # Figure 2: mean across test mice
    fig, axes = plt.subplots(1, 2, figsize=(10, 4.6))
    mean_acc = [np.mean([per_fold_group[m]["models"][mk]["accuracy"] for m in fold_order]) for mk in model_order]
    mean_f1 = [np.mean([per_fold_group[m]["models"][mk]["macro_f1"] for m in fold_order]) for mk in model_order]
    std_acc = [np.std([per_fold_group[m]["models"][mk]["accuracy"] for m in fold_order]) for mk in model_order]
    std_f1 = [np.std([per_fold_group[m]["models"][mk]["macro_f1"] for m in fold_order]) for mk in model_order]
    xi = np.arange(len(model_order))

    axes[0].bar(xi, mean_acc, yerr=std_acc, capsize=4, color=[colors[m] for m in model_order], alpha=0.85)
    axes[0].set_xticks(xi)
    axes[0].set_xticklabels([model_titles[m] for m in model_order], rotation=25, ha="right", fontsize=8)
    axes[0].set_ylim(0, 1.05)
    axes[0].set_ylabel("Accuracy")
    axes[0].set_title(f"Mean accuracy across test mice ({group_name}, {grid_mode_label})")
    axes[0].grid(axis="y", alpha=0.25)

    axes[1].bar(xi, mean_f1, yerr=std_f1, capsize=4, color=[colors[m] for m in model_order], alpha=0.85)
    axes[1].set_xticks(xi)
    axes[1].set_xticklabels([model_titles[m] for m in model_order], rotation=25, ha="right", fontsize=8)
    axes[1].set_ylim(0, 1.05)
    axes[1].set_ylabel("Macro-F1")
    axes[1].set_title(f"Mean macro-F1 across test mice ({group_name}, {grid_mode_label})")
    axes[1].grid(axis="y", alpha=0.25)

    fig.tight_layout()
    fig2 = figures_dir / f"02_lomo_mean_scores_{group_name}.png"
    fig.savefig(fig2, dpi=300, bbox_inches="tight")
    plt.close(fig)
    written.append(fig2)

    # Figure 3: normalized confusion matrices (rows=test mice, cols=models)
    n_mice = len(fold_order)
    n_models = len(model_order)
    fig, axes = plt.subplots(
        n_mice,
        n_models,
        figsize=(4.4 * n_models, 3.8 * n_mice),
        squeeze=False,
    )
    for row_idx, mouse_name in enumerate(fold_order):
        payload = confusion_group[mouse_name]
        labels_order = payload["labels"]
        best_model = payload["best_model"]
        for col_idx, mk in enumerate(model_order):
            ax = axes[row_idx][col_idx]
            cm_arr = np.asarray(payload["cms"][mk], dtype=float)
            row_sums = cm_arr.sum(axis=1, keepdims=True)
            cm_norm = np.divide(cm_arr, row_sums, out=np.zeros_like(cm_arr), where=row_sums != 0)
            ConfusionMatrixDisplay(cm_norm, display_labels=labels_order).plot(
                ax=ax,
                cmap="Blues",
                colorbar=False,
                values_format=".2f",
            )
            title = f"{_short_mouse_name(mouse_name)}\\n{model_titles[mk]}"
            if mk == best_model:
                title += " ★"
            ax.set_title(title, fontsize=7)

    fig.suptitle(
        f"Normalized confusion matrices ({group_name}, {grid_mode_label}) - all classifiers per test mouse (★ = best)",
        fontsize=11,
    )
    fig.tight_layout()
    fig3 = figures_dir / f"03_all_classifier_confusion_matrices_{group_name}.png"
    fig.savefig(fig3, dpi=300, bbox_inches="tight")
    plt.close(fig)
    written.append(fig3)

    return written


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = _build_parser()
    args = parser.parse_args()

    model_order = _resolve_models(args.models)
    zz_folder = args.zz_folder or _build_zz_folder(args.p_active, args.per_trial_thresh)

    # Discover / validate mice
    discovered = _discover_mice(args.data_root)
    eligible_mice = validate_mice_for_ablation(
        args.mice, args.data_root, args.meta_root, discovered
    )
    if not eligible_mice:
        print("ERROR: No eligible mice found.", file=sys.stderr)
        sys.exit(1)
    if len(eligible_mice) < 2:
        print("ERROR: Cross-mouse analysis requires at least 2 eligible mice.", file=sys.stderr)
        sys.exit(1)

    # Determine clip frames
    if args.clip_frames is not None:
        global_clip = int(args.clip_frames)
    else:
        print("Pre-scanning valid_frames for global clip ...", flush=True)
        min_list = []
        for mn in eligible_mice:
            try:
                _, _, _, vf = load_labelled_barcodes(
                    args.data_root, args.meta_root, mn, zz_folder, max_trials=args.max_trials
                )
                if len(vf) > 0:
                    min_list.append(int(vf.min()))
            except Exception:
                pass
        if not min_list:
            print("ERROR: Could not determine global clip_frames.", file=sys.stderr)
            sys.exit(1)
        global_clip = min(min_list)
        print(f"  global_clip_frames = {global_clip}", flush=True)

    # ---- PREFLIGHT CHECKS --------------------------------------------------
    print("\nRunning preflight checks ...", flush=True)
    sampled_ids = _preflight_check(
        eligible_mice=eligible_mice,
        data_root=args.data_root,
        cache_dir=args.cache_dir,
        shuffle_type=args.shuffle_type,
        method=args.vectorization_method,
        p_active=args.p_active,
        per_trial_thresh=args.per_trial_thresh,
        clip_frames=global_clip,
        different_shuffle_per_trial=args.different_shuffle_per_trial,
        n_shuffles=args.n_shuffles,
        max_trials=args.max_trials,
        seed=args.seed,
    )
    print(f"Preflight PASSED. Sampled shuffle IDs (same for all mice): {sampled_ids}", flush=True)
    # -------------------------------------------------------------------------

    mode_token = _shuffle_mode_token(args.different_shuffle_per_trial)
    output_dir = args.output_folder / mode_token
    output_dir.mkdir(parents=True, exist_ok=True)
    figures_dir = output_dir / "figures"
    logs_dir = output_dir / "logs"
    figures_dir.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)
    log_path = logs_dir / "run.log"

    device = _resolve_device(args.device)
    _set_seed(args.seed)

    fs = _FakeState(cache_dir=args.cache_dir, data_root=args.data_root)

    with open(log_path, "w", encoding="utf-8") as log_fp, \
         redirect_stdout(log_fp), redirect_stderr(log_fp):

        print("=" * 90)
        print("Cross-Mouse LOMO Classification on Shuffled Vectorizations")
        print(f"Timestamp: {datetime.now().isoformat(timespec='seconds')}")
        print("=" * 90)
        print(f"  output_folder        : {output_dir}")
        print(f"  shuffle_type         : {args.shuffle_type}")
        print(f"  n_shuffles (sampled) : {args.n_shuffles}")
        print(f"  sampled_ids          : {sampled_ids}")
        print(f"  shuffle_mode         : {mode_token}")
        print(f"  method               : {args.vectorization_method}")
        print(f"  p_active             : {args.p_active}")
        print(f"  clip_frames          : {global_clip}")
        print(f"  models               : {model_order}")
        print(f"  device               : {device}")
        print(f"  seed                 : {args.seed}")

        grid_mode_label = _grid_mode_label(model_order)

        all_results: Dict[int, Dict[str, Any]] = {}  # {shuffle_id: {test_mouse: result}}
        all_cms: Dict[int, Dict[str, Any]] = {}

        for shuffle_id in sampled_ids:
            print(f"\n{'='*80}")
            print(f"Shuffle ID: {shuffle_id}")
            print(f"{'='*80}")

            # Load all mice data for this shuffle
            mouse_data: Dict[str, Optional[Dict[str, Any]]] = {}
            for mouse_name in eligible_mice:
                base_stem = build_vectorization_cache_stem(
                    mouse_name=mouse_name,
                    method=args.vectorization_method,
                    p_active=args.p_active,
                    per_trial_thresh=args.per_trial_thresh,
                    clip_frames=global_clip,
                )
                mcdir = _resolve_mouse_cache_dir(fs, mouse_name)
                shuffle_stem = _shuffle_cache_stem_with_mode(
                    base_stem,
                    args.shuffle_type,
                    shuffle_id,
                    args.different_shuffle_per_trial,
                )
                cache_path = mcdir / f"{shuffle_stem}.npz"

                print(f"  Loading {mouse_name[-30:]} ...", end=" ", flush=True)
                try:
                    data = _load_mouse_shuffle_data(
                        mouse_name=mouse_name,
                        shuffle_id=shuffle_id,
                        cache_path=cache_path,
                        clip_frames=global_clip,
                    )
                    mouse_data[mouse_name] = data
                    status = "ok" if data is not None else "skipped (insufficient labels)"
                    print(status)
                except Exception as exc:
                    print(f"FAILED: {exc}")
                    traceback.print_exc()
                    mouse_data[mouse_name] = None

            # Run LOMO
            per_fold, cm_payload = _run_cross_mouse_one_shuffle(
                shuffle_id=shuffle_id,
                eligible_mice=eligible_mice,
                mouse_data=mouse_data,
                clip_frames=global_clip,
                model_order=model_order,
                device=device,
                epochs_mlp=args.epochs_mlp,
                epochs_cnn1d=args.epochs_cnn1d,
                epochs_cnn3d=args.epochs_cnn3d,
                lr_vec=args.lr_vec,
                lr_cnn3d=args.lr_cnn3d,
                batch_size_vec=args.batch_size_vec,
                batch_size_grid=args.batch_size_grid,
                weight_decay=args.weight_decay,
                early_stop_patience=args.early_stop_patience,
                num_workers_dl=args.num_workers_dl,
                seed=args.seed,
            )
            all_results[shuffle_id] = per_fold
            all_cms[shuffle_id] = cm_payload
            gc.collect()

        # ---- Save figures ---------------------------------------------------
        print("\nSaving LOMO summary figures (per shuffle + average across shuffles) ...", flush=True)
        written_figures: List[Path] = []

        # Per-shuffle figure sets
        for shuffle_id in sorted(all_results.keys()):
            per_fold_group = all_results.get(shuffle_id, {})
            confusion_group = all_cms.get(shuffle_id, {})
            if per_fold_group and confusion_group:
                gname = f"shuffle{int(shuffle_id):04d}"
                written_figures.extend(
                    _save_lomo_summary_figures_for_group(
                        group_name=gname,
                        per_fold_group=per_fold_group,
                        confusion_group=confusion_group,
                        figures_dir=figures_dir,
                        method=args.vectorization_method,
                        grid_mode_label=grid_mode_label,
                        model_order=model_order,
                    )
                )

        # Average-across-shuffles figure set
        avg_per_fold: Dict[str, Dict[str, Any]] = {}
        avg_cms: Dict[str, Dict[str, Any]] = {}
        test_mice_present = sorted({tm for fold in all_results.values() for tm in fold.keys()})
        for test_mouse in test_mice_present:
            available_shuffle_ids = [sid for sid, fold in all_results.items() if test_mouse in fold]
            if not available_shuffle_ids:
                continue

            _all_model_keys = list(model_order)
            avg_models = {
                mk: {
                    "accuracy": float(np.mean([float(all_results[sid][test_mouse]["models"][mk]["accuracy"]) for sid in available_shuffle_ids])),
                    "macro_f1": float(np.mean([float(all_results[sid][test_mouse]["models"][mk]["macro_f1"]) for sid in available_shuffle_ids])),
                    "std_accuracy": float(np.std([float(all_results[sid][test_mouse]["models"][mk]["accuracy"]) for sid in available_shuffle_ids])),
                    "std_macro_f1": float(np.std([float(all_results[sid][test_mouse]["models"][mk]["macro_f1"]) for sid in available_shuffle_ids])),
                }
                for mk in _all_model_keys
            }
            best_model = max(_all_model_keys, key=lambda m: avg_models[m]["macro_f1"])

            first_row = all_results[available_shuffle_ids[0]][test_mouse]
            avg_per_fold[test_mouse] = {
                "shuffle_id": "avg",
                "test_mouse": test_mouse,
                "train_mice": first_row["train_mice"],
                "n_train_mice": int(first_row["n_train_mice"]),
                "n_train_trials": int(first_row["n_train_trials"]),
                "n_test_trials": int(first_row["n_test_trials"]),
                "n_features": int(first_row["n_features"]),
                "clip_frames": int(first_row["clip_frames"]),
                "shared_labels": list(first_row["shared_labels"]),
                "n_classes": int(first_row["n_classes"]),
                "best_model": best_model,
                "models": {
                    mk: {"accuracy": avg_models[mk]["accuracy"], "macro_f1": avg_models[mk]["macro_f1"]}
                    for mk in _all_model_keys
                },
            }

            cm_available_ids = [sid for sid, cms in all_cms.items() if test_mouse in cms]
            if cm_available_ids:
                labels_order = list(all_cms[cm_available_ids[0]][test_mouse]["labels"])
                avg_cms[test_mouse] = {
                    "labels": labels_order,
                    "cms": {
                        mk: np.mean(
                            np.stack([np.asarray(all_cms[sid][test_mouse]["cms"][mk], dtype=float) for sid in cm_available_ids], axis=0),
                            axis=0,
                        )
                        for mk in _all_model_keys
                    },
                    "best_model": best_model,
                }

        if avg_per_fold and avg_cms:
            written_figures.extend(
                _save_lomo_summary_figures_for_group(
                    group_name="avg_across_shuffles",
                    per_fold_group=avg_per_fold,
                    confusion_group=avg_cms,
                    figures_dir=figures_dir,
                    method=args.vectorization_method,
                    grid_mode_label=grid_mode_label,
                    model_order=model_order,
                )
            )

        # ---- Save JSON / CSV ------------------------------------------------
        json_path = output_dir / "cross_mouse_ablation_shuffle_metrics.json"
        csv_path = output_dir / "cross_mouse_ablation_shuffle_metrics.csv"

        payload_json = {
            "method": args.vectorization_method,
            "p_active": args.p_active,
            "shuffle_type": args.shuffle_type,
            "different_shuffle_per_trial": args.different_shuffle_per_trial,
            "shuffle_mode": mode_token,
            "models": model_order,
            "n_shuffles_requested": args.n_shuffles,
            "seed": args.seed,
            "eligible_mice": eligible_mice,
            "sampled_shuffle_ids": sampled_ids,
            "per_shuffle": all_results,
            "figures": [str(p) for p in written_figures],
        }
        with open(json_path, "w", encoding="utf-8") as fp:
            json.dump(payload_json, fp, indent=2)
        print(f"Wrote JSON: {json_path}")

        with open(csv_path, "w", encoding="utf-8", newline="") as fp:
            writer = csv.writer(fp)
            writer.writerow([
                "shuffle_mode",
                "different_shuffle_per_trial",
                "shuffle_id", "test_mouse", "model",
                "n_train_trials", "n_test_trials",
                "accuracy", "macro_f1",
                "best_model",
            ])
            for shuffle_id, fold_results in all_results.items():
                for test_mouse, row in fold_results.items():
                    for mk in model_order:
                        mr = row["models"][mk]
                        writer.writerow([
                            mode_token,
                            args.different_shuffle_per_trial,
                            shuffle_id,
                            test_mouse,
                            mk,
                            row["n_train_trials"],
                            row["n_test_trials"],
                            mr["accuracy"],
                            mr["macro_f1"],
                            row["best_model"],
                        ])
        print(f"Wrote CSV : {csv_path}")

        print("\n" + "=" * 90)
        print("SUCCESS")
        print("=" * 90)

    print(f"Done. Results: {output_dir}", flush=True)


if __name__ == "__main__":
    main()
